---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: student-information-system
  name: student-information-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-information-system
  template:
    metadata:
      labels:
        app: student-information-system
        visualize: "true"
    spec:
      containers:
        - name: student-information-system
          image: arthurstrokov/student-information-system:v0.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: EUREKA-DEFAULT-ZONE
              value: "http://eureka-server:8761/eureka/"
            - name: CONFIG_URL
              value: 192.168.59.106:30372/cloud-configuration-server
            - name: spring.mvc.servlet.path
              value: /student-information-system
            - name: SERVER-PORT
              value: "8080"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: student-information-system
  name: student-information-system
  annotations:
    haproxy.org/check: "enabled"
    haproxy.org/forwarded-for: "enabled"
    haproxy.org/load-balance: "roundrobin"
    haproxy.org/path-rewrite: /
spec:
  selector:
    app: student-information-system
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
