spring:
  main:
    banner-mode: "off"
  application:
    name: student-information-system
  config:
    import: 'optional:configserver:'
  profiles:
    active: cloud # dev cloud
  cloud:
    config:
      enabled: true
      failFast: true
      uri: http://${CONFIG_URL}/
---
server:
  port: 8080
