spring:
  data:
    mongodb: # mongodb
      host: ${MONGODB_HOST} # for using in Virtualbox Minikube Kubernetes instead of localhost
      port: 27017
      database: test
---
# logging
logging:
  level:
    org:
      springframework:
        data: info
