spring:
  main:
    banner-mode: "off"
  application:
    name: student-information-system
  config:
    import: 'optional:configserver:'
  profiles:
    active: cloud # dev cloud
  cloud:
    config:
      enabled: true
      failFast: true
      discovery:
        enabled: true
        service-id: cloud-configuration-server
#      uri: http://${CONFIG_URL:localhost:8888}/
---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: false
---
server:
  port: 8080
--- # Actuator
management:
  endpoints:
    web:
      exposure:
        include: ["*"]
